"use client";
import {useEffect,useState} from "react";import {BookOpen,FileText,LockKeyhole} from "lucide-react";
export default function ResourcesClient(){
 const [data,setData]=useState<any>(null),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/lockliel/resources",{cache:"no-store"}).then(async r=>{if(r.status===401){location.assign("/my-lockliel/sign-in");return;}const d=await r.json();if(!r.ok){setError(d.error||"Unable to load resources.");return;}setData(d);});},[]);
 async function openResource(productId:string){const r=await fetch("/api/lockliel/resources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({productId})});if(!r.ok){const d=await r.json().catch(()=>({}));setError(d.error||"Unable to open resource.");return;}const blob=await r.blob(),url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000);}
 if(error)return <p className="ml-auth-message error">{error}</p>;if(!data)return <div className="ml-loading">Loading your resources…</div>;
 if(!data.resources.length)return <section className="ml-card"><div className="ml-icon"><LockKeyhole size={21}/></div><h2>Your resource library is ready.</h2><p>Digital books and resources you purchase or receive will appear here automatically. A Heart for the Lost is being prepared for its digital release.</p></section>;
 return <section className="ml-grid">{data.resources.map((r:any)=><article className="ml-card" key={r.id}><div className="ml-icon">{r.product.product_type==="digital_book"?<BookOpen size={21}/>:<FileText size={21}/>}</div><div className="ml-kicker">{r.product.product_type.replaceAll("_"," ")}</div><h2>{r.product.title}</h2><p>{r.product.description||"Your Lockliel resource."}</p><small className="ml-resource-grant">Added {new Date(r.granted_at).toLocaleDateString()}</small><button className="ml-action" onClick={()=>openResource(r.product.id)}>Open resource</button></article>)}</section>;
}