import test from "node:test";
import assert from "node:assert/strict";
import { createReleaseSignup } from "../netlify/functions/book-release.mjs";
function memory(){const data=new Map();let version=0;return {data,async get(k){return data.get(k)?.value??null},async getWithMetadata(k){return data.get(k)??null},async setJSON(k,value,opts={}){const prior=data.get(k);if(opts.onlyIfNew&&prior||opts.onlyIfMatch&&prior?.etag!==opts.onlyIfMatch)return {modified:false};data.set(k,{value:structuredClone(value),data:structuredClone(value),etag:String(++version)});return {modified:true}}};}
const valid={firstName:"QA Test",email:"qa@example.com",releaseConsent:true,attribution:{utm_source:"facebook",utm_campaign:"book-launch"}};
const request=(data,origin="https://lockliel.com")=>new Request("https://lockliel.com/api/book-release",{method:"POST",headers:{Origin:origin,"Content-Type":"application/json"},body:JSON.stringify(data)});
test("captures book-specific consent and source without general marketing, deduplicates concurrent requests",async()=>{const store=memory();let posts=0;const fn=createReleaseSignup({storeFor:()=>store,post:async()=>{posts++;return new Response("ok")}});const responses=await Promise.all([fn(request(valid)),fn(request({...valid,email:"QA@example.com"}))]);assert(responses.every(r=>r.status===200));assert.equal(posts,1);const leads=[...store.data.entries()].filter(([k])=>k.includes('/leads/'));assert.equal(leads.length,1);assert.equal(leads[0][1].value.book,"A Heart for the Lost");assert.equal(leads[0][1].value.generalMarketingConsent,false);assert.equal(leads[0][1].value.attribution.utm_source,"facebook");assert.deepEqual(await responses[0].json(),{ok:true});});
test("invalid and unsolicited requests fail without saving",async()=>{const store=memory();const fn=createReleaseSignup({storeFor:()=>store});for(const data of [{...valid,firstName:" "},{...valid,email:"bad"},{...valid,releaseConsent:false},{...valid,botField:"spam"}])assert.equal((await fn(request(data))).status,400);assert.equal((await fn(request(valid,"https://foreign.example"))).status,403);assert.equal(store.data.size,0);});
test("storage outage reports failure; Forms outage preserves durable signup and retries",async()=>{const broken=createReleaseSignup({storeFor:()=>{throw Error('offline')}});assert.equal((await broken(request(valid))).status,503);const store=memory();let posts=0;const fn=createReleaseSignup({storeFor:()=>store,post:async()=>{posts++;return new Response("offline",{status:503})}});assert.equal((await fn(request(valid))).status,200);assert.equal((await fn(request(valid))).status,200);assert.equal(posts,2);assert.equal([...store.data.values()].filter(x=>x.value.email).length,1);});
