"use client";
import {useEffect,useMemo,useState} from "react";import {Check,MessageCircle,Send,Users} from "lucide-react";
type Card={profile_id:string;first_name?:string;last_initial?:string;city?:string;region?:string;country?:string};
type Message={id:number;sender_id:string;body:string;created_at:string};
type Conversation={id:string;other:Card|null;messages:Message[]};
export default function ConnectionsClient(){
 const [data,setData]=useState<{conversations:Conversation[];tasks:any[];messagingEnabled?:boolean}|null>(null),[error,setError]=useState(""),[drafts,setDrafts]=useState<Record<string,string>>({});
 async function load(){const r=await fetch("/api/lockliel/connections",{cache:"no-store"});if(r.status===401){location.assign("/my-lockliel/sign-in");return;}const d=await r.json();if(!r.ok){setError(d.error||"Unable to load connections.");return;}setData(d);}
 useEffect(()=>{load();},[]);
 async function send(id:string){if(data?.messagingEnabled===false)return;const body=(drafts[id]||"").trim();if(!body)return;const r=await fetch("/api/lockliel/connections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"sendMessage",conversationId:id,body})});if(r.ok){setDrafts(v=>({...v,[id]:""}));await load();}}
 async function complete(taskId:string){const r=await fetch("/api/lockliel/connections",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"completeTask",taskId})});if(r.ok)await load();}
 const people=useMemo(()=>data?.conversations.filter(c=>c.other)||[],[data]);
 if(error)return <p className="ml-auth-message error">{error}</p>;if(!data)return <div className="ml-loading">Loading your connections…</div>;
 return <><section className="ml-connection-summary"><article className="ml-card"><div className="ml-icon"><Users size={20}/></div><strong>{people.length}</strong><span>active connections</span></article><article className="ml-card"><div className="ml-icon"><Check size={20}/></div><strong>{data.tasks.length}</strong><span>follow-ups to do</span></article></section>
 {data.tasks.length>0&&<section className="ml-panel ml-followups"><div className="ml-kicker">Follow up</div><h2>People worth checking on</h2>{data.tasks.map(t=><div className="ml-followup-row" key={t.id}><div><b>{t.notes||"Follow up"}</b><span>{t.due_at?"Due "+new Date(t.due_at).toLocaleDateString():""}</span></div><button onClick={()=>complete(t.id)}><Check size={15}/> Done</button></div>)}</section>}
 <h2 className="ml-section-title">My connections</h2>{people.length===0?<section className="ml-card"><div className="ml-icon"><MessageCircle size={20}/></div><h2>Your connections will appear here.</h2><p>When someone joins through your personal Lockliel invitation, you can follow up inside Lockliel without needing their private email or phone number.</p></section>:<section className="ml-conversation-grid">{people.map(c=><article className="ml-panel ml-conversation" key={c.id}><div className="ml-conversation-person"><div className="ml-avatar">{(c.other?.first_name||"?").slice(0,1)}</div><div><h3>{c.other?.first_name}{c.other?.last_initial?" "+c.other.last_initial+".":""}</h3><span>{[c.other?.city,c.other?.region].filter(Boolean).join(", ")}</span></div></div><div className="ml-message-thread">{c.messages.length?c.messages.slice(-6).map(m=><p key={m.id}>{m.body}<small>{new Date(m.created_at).toLocaleString()}</small></p>):<p className="ml-empty-message">Send a welcome message when you're ready.</p>}</div><div className="ml-message-compose"><input disabled={data.messagingEnabled===false} value={drafts[c.id]||""} onChange={e=>setDrafts(v=>({...v,[c.id]:e.target.value}))} placeholder={data.messagingEnabled===false?"Messaging temporarily unavailable":"Write a message…"}/><button disabled={data.messagingEnabled===false} onClick={()=>send(c.id)} aria-label="Send message"><Send size={17}/></button></div></article>)}</section>}</>;
}