import type { Metadata } from "next";
import BookReleaseSignup from "@/components/book-release-signup";
import "../who-god-says-you-are/resource.css";
import styles from "./release.module.css";
const title="A Heart for the Lost | Coming Soon | Lockliel";
const description="A practical, faith-building mini-book by David Fowler on God’s heart for people and our Great Co-Mission. Sign up for the release announcement.";
export const metadata: Metadata={title,description,alternates:{canonical:"https://lockliel.com/a-heart-for-the-lost"},openGraph:{title,description,url:"https://lockliel.com/a-heart-for-the-lost",type:"website",images:[{url:"https://lockliel.com/heart-for-the-lost/cover.jpg",width:800,height:1228,alt:"A Heart for the Lost by David Fowler"}]},twitter:{card:"summary_large_image",title,description,images:["https://lockliel.com/heart-for-the-lost/cover.jpg"]}};
export default function HeartBookPage() {
 return <div className="fb-resource">
  <header className="fr-header fr-shell"><a className="fr-brand" href="/"><img src="/lockliel-mark.png" width={44} height={44} alt=""/><span>Lockliel<small>REACH. TEACH. TRAIN. DISCIPLE.</small></span></a><a className="fr-nav-link" href="#release-notify">Get notified ↗</a></header>
  <main>
   <section className="fr-hero"><div className="fr-shell fr-hero-grid"><div><p className="fr-eyebrow">Coming soon · A Lockliel resource</p><h1>A Heart<br/>for the <em>Lost.</em></h1><p className="fr-subtitle">God’s Heart for People and Our Great Co-Mission</p><p className="fr-lead">One person matters. Your story matters. God can use your life to help someone discover Jesus.</p><p className="fr-final-word">A practical, faith-building mini-book<br/><strong>By David Fowler</strong></p><a className="fr-button fr-primary" href="#release-notify">Get notified when it releases ↓</a><p className="fr-micro">Coming soon. Join the release-notification list.</p></div><figure className="fr-cover"><img src="/heart-for-the-lost/cover.jpg" width={800} height={1228} fetchPriority="high" alt="A Heart for the Lost, a mini-book on God’s heart for people and our great co-mission, by David Fowler"/><figcaption><span>One person matters.</span><span>Coming soon</span></figcaption></figure></div></section>
   <section className="fr-discover"><div className="fr-shell"><div className="fr-section-heading"><div><p className="fr-eyebrow">The Father’s heart. Your everyday life.</p><h2>See people<br/><em>through His eyes.</em></h2></div><p><em>A Heart for the Lost</em> helps believers rediscover the Father’s heart for people and step confidently into the mission Jesus gave His Church. It is not about becoming a professional evangelist. It is about recognizing that one person matters, your story matters, and God can use your life to help someone discover Jesus.</p></div><p className={styles.description}>Through Scripture, real-life stories, and simple steps you can put into practice, the book explores the value God places on every person, how Jesus reached people where they were, how to share your testimony, how to overcome fear, and how ordinary believers can participate in the Great Co-Mission.</p><div className={styles.steps} aria-label="The heartbeat of the book"><div><span>01 / REACH</span><h3>Reach one.</h3></div><div><span>02 / HELP GROW</span><h3>Help that one grow.</h3></div><div><span>03 / MULTIPLY</span><h3>Teach that one<br/>to reach one.</h3></div></div><p className={styles.mission}>Reach. Teach. Train. Disciple.<br/><span>Duplication. Multiplication.</span></p><p className={styles.description}>This is more than a book about evangelism. It is an invitation to live with purpose, see people through the Father’s eyes, and become part of a multiplying movement of believers carrying the Gospel beyond the walls.</p><details className={styles.preview}><summary>Take a look at the back cover <span aria-hidden="true">+</span></summary><img src="/heart-for-the-lost/back-cover.jpg" width={976} height={1458} loading="lazy" alt="Back cover of A Heart for the Lost. One person matters. Inside: every person’s eternal value, Jesus’ example of love, sharing your story, and helping others grow and reach one."/></details></div></section>
   <section id="release-notify" className="fr-optin"><div className="fr-shell fr-optin-grid"><div className="fr-optin-copy"><p className="fr-eyebrow">Coming soon</p><h2>Your next step<br/><em>starts with one.</em></h2><p>Be among the first to know when <strong>A Heart for the Lost</strong> is released. Leave your name and email, and we’ll keep your place on the notification list.</p><p>Until then, let God use your life to reach someone right where they are.</p></div><BookReleaseSignup/></div></section>
  </main><footer className="fr-footer fr-shell"><a href="/">Lockliel.com</a><p>Empowering and Mobilizing the Church Beyond the Walls.</p><a href="/#faith-boost">Watch Faith Boost ↗</a></footer>
 </div>;
}
