-- Read-only, version-independent catalog fingerprint. No member data or query text.
select jsonb_build_object(
 'ledger',coalesce((select jsonb_agg(jsonb_build_object('version',version,'name',name,'statements_md5',md5(statements::text)) order by version) from supabase_migrations.schema_migrations),'[]'),
 'tables',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'rls',c.relrowsecurity,'acl',(select jsonb_agg(x order by x) from unnest(c.relacl::text[]) x)) order by n.nspname,c.relname) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','app_private') and c.relkind='r' and c.relname in ('courses','lessons','lesson_assets','course_enrollments','lesson_progress','media_progress','lesson_private_notes','course_answer_keys')),
 'columns',(select jsonb_agg(jsonb_build_object('table',c.relname,'column',a.attname,'type',format_type(a.atttypid,a.atttypmod),'notnull',a.attnotnull,'default',pg_get_expr(d.adbin,d.adrelid)) order by c.relname,a.attnum) from pg_class c join pg_namespace n on n.oid=c.relnamespace join pg_attribute a on a.attrelid=c.oid and a.attnum>0 and not a.attisdropped left join pg_attrdef d on d.adrelid=c.oid and d.adnum=a.attnum where n.nspname in ('public','app_private') and c.relname in ('courses','lessons','lesson_assets','lesson_progress','media_progress','lesson_private_notes','course_answer_keys')),
 'functions',(select jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'args',pg_get_function_identity_arguments(p.oid),'definition',md5(pg_get_functiondef(p.oid)),'owner',pg_get_userbyid(p.proowner),'acl',(select jsonb_agg(x order by x) from unnest(p.proacl::text[]) x)) order by n.nspname,p.proname) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','app_private') and p.proname in ('lockliel_sample_media','lockliel_save_lesson','lockliel_course_gates','course_watch_met','course_lesson_unlocked','normalize_lesson_asset_duration_verification','validate_lesson_completion','validate_course_release','audit_learning_configuration')),
 'constraints',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',k.conname,'valid',k.convalidated,'definition',pg_get_constraintdef(k.oid)) order by c.relname,k.conname) from pg_constraint k join pg_class c on c.oid=k.conrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname in ('public','app_private') and c.relname in ('courses','lessons','lesson_assets','lesson_progress','media_progress','lesson_private_notes','course_answer_keys')),
 'policies',(select jsonb_agg(to_jsonb(p) order by schemaname,tablename,policyname) from pg_policies p where schemaname in ('public','app_private') and tablename in ('courses','lessons','lesson_assets','course_enrollments','lesson_progress','media_progress','lesson_private_notes','course_answer_keys')),
 'triggers',(select jsonb_agg(jsonb_build_object('table',c.relname,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid)) order by c.relname,t.tgname) from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and not t.tgisinternal and c.relname in ('courses','lessons','lesson_assets','course_enrollments','lesson_progress','media_progress','lesson_private_notes')),
 'column_grants',(select jsonb_agg(to_jsonb(g) - 'table_catalog' order by table_schema,table_name,column_name,grantee,privilege_type) from information_schema.column_privileges g where table_schema='public' and table_name in ('courses','lessons','lesson_assets','lesson_progress','media_progress','lesson_private_notes') and grantee in ('anon','authenticated','PUBLIC'))
) as catalog;
