"use client";
import {useEffect,useMemo,useState} from "react";import {BookOpen,CheckCircle2,Circle,PlayCircle} from "lucide-react";
export default function JourneyClient(){
 const [data,setData]=useState<any>(null),[error,setError]=useState("");
 async function load(){const r=await fetch("/api/lockliel/journey",{cache:"no-store"});if(r.status===401){location.assign("/my-lockliel/sign-in");return;}const d=await r.json();if(!r.ok){setError(d.error||"Unable to load your journey.");return;}setData(d);}
 useEffect(()=>{load();},[]);
 const progressMap=useMemo(()=>Object.fromEntries((data?.progress||[]).map((p:any)=>[p.lesson_id,p])),[data]);
 async function start(lessonId:string){await fetch("/api/lockliel/journey",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({lessonId,status:"in_progress"})});await load();}
 if(error)return <p className="ml-auth-message error">{error}</p>;if(!data)return <div className="ml-loading">Loading your journey…</div>;
 if(!data.course)return <section className="ml-card"><BookOpen/><h2>Your first course will appear here.</h2><p>Complete your profile and faith journey so we can open your foundational discipleship path.</p></section>;
 const completed=(data.progress||[]).filter((p:any)=>p.status==="completed").length,total=data.lessons.length,percent=total?Math.round(completed/total*100):0;
 return <><section className="ml-course-overview"><div><div className="ml-kicker">Foundational discipleship</div><h2>{data.course.title}</h2><p>{data.course.description}</p></div><div className="ml-course-percent"><strong>{percent}%</strong><span>{completed} of {total} complete</span></div></section><div className="ml-course-progress"><span style={{width:percent+"%"}}/></div><section className="ml-lesson-list">{data.lessons.map((lesson:any)=>{const p=progressMap[lesson.id],status=p?.status||"not_started";return <article className={"ml-lesson-row "+status} key={lesson.id}><div className="ml-lesson-number">{status==="completed"?<CheckCircle2 size={20}/>:status==="in_progress"?<PlayCircle size={20}/>:<Circle size={20}/>}</div><div className="ml-lesson-copy"><span>Lesson {lesson.position}</span><h3>{lesson.title}</h3><small>{status==="completed"?"Completed":status==="in_progress"?"In progress":"Not started"}</small></div><button onClick={()=>start(lesson.id)} disabled={status==="completed"}>{status==="completed"?"Complete":status==="in_progress"?"Continue":"Start"}</button></article>})}</section><p className="ml-privacy-note" style={{marginTop:18}}>Video, worksheet, and resume-position tracking are built into this course structure. Lesson media and worksheets will be connected as those assets are brought into Lockliel.</p></>;
}