select jsonb_build_object(
'columns',(select jsonb_agg(jsonb_build_object('table',c.table_name,'column',c.column_name,'type',c.udt_name,'nullable',c.is_nullable,'default',c.column_default) order by c.table_name,c.ordinal_position) from information_schema.columns c where c.table_schema='public' and c.table_name in ('founders50_reviews','share_assets')),
'constraints',(select jsonb_agg(jsonb_build_object('table',r.relname,'name',c.conname,'definition',pg_get_constraintdef(c.oid),'validated',c.convalidated) order by r.relname,c.conname) from pg_constraint c join pg_class r on r.oid=c.conrelid where c.conrelid in ('public.founders50_reviews'::regclass,'public.share_assets'::regclass)),
'indexes',(select jsonb_agg(jsonb_build_object('table',tablename,'name',indexname,'definition',indexdef) order by tablename,indexname) from pg_indexes where schemaname='public' and tablename in ('founders50_reviews','share_assets')),
'policies',(select jsonb_agg(jsonb_build_object('table',tablename,'name',policyname,'permissive',permissive,'roles',roles,'cmd',cmd,'qual',qual,'check',with_check) order by tablename,policyname) from pg_policies where schemaname='public' and tablename in ('founders50_reviews','share_assets')),
'triggers',(select jsonb_agg(jsonb_build_object('table',r.relname,'name',t.tgname,'enabled',t.tgenabled,'definition',pg_get_triggerdef(t.oid)) order by r.relname,t.tgname) from pg_trigger t join pg_class r on r.oid=t.tgrelid where not t.tgisinternal and t.tgrelid in ('public.founders50_reviews'::regclass,'public.share_assets'::regclass)),
'rls',(select jsonb_agg(jsonb_build_object('table',relname,'rls',relrowsecurity,'force',relforcerowsecurity) order by relname) from pg_class where oid in ('public.founders50_reviews'::regclass,'public.share_assets'::regclass)),
'grants',(select jsonb_agg(jsonb_build_object('table',table_name,'role',grantee,'privilege',privilege_type,'grantable',is_grantable) order by table_name,grantee,privilege_type) from information_schema.role_table_grants where table_schema='public' and table_name in ('founders50_reviews','share_assets') and grantee in ('anon','authenticated','service_role')),
'column_grants',(select jsonb_agg(jsonb_build_object('table',table_name,'column',column_name,'role',grantee,'privilege',privilege_type) order by table_name,column_name,grantee,privilege_type) from information_schema.role_column_grants where table_schema='public' and table_name in ('founders50_reviews','share_assets') and grantee in ('anon','authenticated','service_role'))
) as schema_snapshot;
