"use client";
import {useState} from "react";import {useRouter} from "next/navigation";
const interests=[["biblical-foundations","Biblical foundations"],["identity-in-christ","Identity in Christ"],["prayer","Prayer"],["faith-development","Growing in faith"],["evangelism","Reaching people"],["discipleship","Discipleship"],["leadership","Leadership"],["healing-wholeness","Healing & wholeness"],["family-relationships","Family & relationships"]];
export default function FaithProfileForm(){
 const router=useRouter();const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const f=new FormData(e.currentTarget);const growthInterests=interests.map(([slug])=>slug).filter(slug=>f.getAll("growthInterests").includes(slug));const r=await fetch("/api/lockliel/faith-profile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({faithStage:f.get("faithStage"),churchBackground:f.get("churchBackground"),ministryExperience:f.get("ministryExperience"),growthInterests,wantsGroup:f.get("wantsGroup")==="yes",wantsHost:f.get("wantsHost")==="yes",preferredConnection:f.get("preferredConnection")})});const d=await r.json();setSaving(false);if(r.status===401){location.assign("/my-lockliel/sign-in");return;}if(!r.ok){setMessage(d.error||"Unable to save.");return;}router.push("/my-lockliel");router.refresh();}
 return <form className="ml-auth-card ml-faith-form" onSubmit={submit}>
  <label>Where would you say you are right now in your faith journey?
   <select name="faithStage" defaultValue=""><option value="">Choose an option</option><option value="exploring">Exploring faith</option><option value="new-believer">New believer</option><option value="growing">Growing in my faith</option><option value="established">Established believer</option><option value="serving-leading">Serving or leading</option><option value="prefer-not-to-answer">Prefer not to answer</option></select>
  </label>
  <label>Church or faith background <span>Optional</span><textarea name="churchBackground" rows={3} placeholder="For example: Baptist, Methodist, Pentecostal, Word of Faith, nondenominational, new to church, or anything else you want us to know."/></label>
  <label>Ministry or serving experience <span>Optional</span><textarea name="ministryExperience" rows={3} placeholder="Tell us only what you are comfortable sharing."/></label>
  <fieldset className="ml-interest-field"><legend>What would you most like to grow in?</legend><div className="ml-interest-grid">{interests.map(([slug,label])=><label key={slug}><input type="checkbox" name="growthInterests" value={slug}/><span>{label}</span></label>)}</div></fieldset>
  <fieldset className="ml-interest-field"><legend>How would you like to connect?</legend><label className="ml-check-line"><input type="checkbox" name="wantsGroup" value="yes"/> I'd like help finding a Lockliel group or gathering.</label><label className="ml-check-line"><input type="checkbox" name="wantsHost" value="yes"/> I'm interested in possibly hosting or helping lead.</label></fieldset>
  <label>Connection preference<select name="preferredConnection" defaultValue="either"><option value="either">Online or local</option><option value="local">Local connection if available</option><option value="online">Online connection</option><option value="not-now">Not right now</option></select></label>
  <p className="ml-privacy-note">This information is private and is used to help personalize discipleship and appropriate ministry follow-up. It is not a public profile.</p>
  {message&&<p className="ml-auth-message error">{message}</p>}<button className="ml-action" disabled={saving}>{saving?"Saving…":"Save and continue"}</button>
 </form>;
}