"use client";
import { useEffect,useState } from "react";
import { useRouter } from "next/navigation";
export default function ProfileForm(){
 const router=useRouter(); const [profile,setProfile]=useState<any>(null); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
 useEffect(()=>{fetch("/api/lockliel-auth/session",{cache:"no-store"}).then(async r=>{if(r.status===401){location.replace("/my-lockliel/sign-in");return;}const d=await r.json();setProfile(d.profile||{});});},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const f=new FormData(e.currentTarget);const r=await fetch("/api/lockliel/profile",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({firstName:f.get("firstName"),lastName:f.get("lastName"),phone:f.get("phone"),city:f.get("city"),region:f.get("region"),country:f.get("country")})});const d=await r.json();setSaving(false);if(!r.ok){setMessage(d.error||"Unable to save.");return;}router.push("/my-lockliel/faith-profile");router.refresh();}
 if(!profile)return <p>Loading your profile…</p>;
 return <form className="ml-auth-card" onSubmit={submit}><div className="ml-auth-row"><label>First name<input name="firstName" defaultValue={profile.first_name||""} required/></label><label>Last name<input name="lastName" defaultValue={profile.last_name||""} required/></label></div><label>Mobile phone <span style={{fontWeight:400,color:"#8fa0ba"}}>Optional</span><input name="phone" type="tel" defaultValue={profile.phone||""}/></label><div className="ml-auth-row"><label>City<input name="city" defaultValue={profile.city||""} required/></label><label>State / region<input name="region" defaultValue={profile.region||""} required/></label></div><label>Country<input name="country" defaultValue={profile.country||"United States"} required/></label>{message&&<p className="ml-auth-message error">{message}</p>}<button className="ml-action" disabled={saving}>{saving?"Saving…":"Save and continue"}</button></form>
}