create temporary table paused_results(name text,result text,scope text);
grant insert on paused_results to authenticated;
do $test$
declare a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); sa uuid:=gen_random_uuid(); sb uuid:=gen_random_uuid(); c uuid; l uuid; l2 uuid; asset uuid; replacement uuid; denied boolean; history_time timestamptz; r jsonb;
begin
 assert public.lockliel_course_cutover_status()='{"paused":true,"schemaReady":true,"protocol":"278-v1"}'::jsonb;
 perform set_config('request.jwt.claims','{}',true);
 insert into auth.users(id,email) values(a,a||'@example.invalid'),(b,b||'@example.invalid');
 insert into auth.sessions(id,user_id,aal) values(sa,a,'aal1'),(sb,b,'aal1');
 insert into public.courses(slug,title,status,translation_key,learning_rules) values('paused280-'||a,'Synthetic paused duration check','published','paused280-'||a,'{"model":"watch_answer","sequential":true,"watch_threshold":95,"minimum_score":0}') returning id into c;
 insert into public.lessons(course_id,position,slug,title,worksheet_schema) values(c,1,'first','Synthetic first','{"questions":[{"number":1,"text":"Synthetic reflection"}]}') returning id into l;
 insert into public.lessons(course_id,position,slug,title,worksheet_schema) values(c,2,'next','Synthetic next','{"questions":[{"number":1,"text":"Synthetic reflection"}]}') returning id into l2;
 insert into public.course_enrollments(profile_id,course_id) values(a,c),(b,c);
 insert into public.lesson_assets(lesson_id,asset_type,provider,provider_ref,status) values(l,'video','youtube','synthetic01','active') returning id into asset;
 assert not app_private.course_watch_met(a,l) and not app_private.course_lesson_unlocked(a,l2);
 insert into paused_results values('case1_missing_no_history','PASS','operator predicate, not authenticated write acceptance');
 insert into public.media_progress(profile_id,asset_id,covered_intervals) values(a,asset,'[[0,50]]');
 assert not app_private.course_watch_met(a,l) and not app_private.course_lesson_unlocked(a,l2);
 insert into paused_results values('case2_missing_partial_history','PASS','operator predicate');
 update public.media_progress set covered_intervals='[[0,95]]' where profile_id=a and asset_id=asset;
 insert into public.lesson_progress(profile_id,lesson_id,status,watch_requirement_met_at) values(a,l,'in_progress',clock_timestamp());
 assert not app_private.course_watch_met(a,l) and not app_private.course_lesson_unlocked(a,l2);
 assert (select covered_intervals='[[0,95]]'::jsonb from public.media_progress where profile_id=a and asset_id=asset);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated','aal','aal1')::text,true);
 perform pg_sleep(0.31);
 execute 'set local role authenticated';
 denied:=false;begin perform public.lockliel_save_lesson(a,l,0,'{"1":"Synthetic answer"}','',true);exception when invalid_parameter_value then denied:=true;end;
 assert denied,'Stale threshold authorized new completion';
 execute 'reset role';perform set_config('request.jwt.claims','{}',true);
 insert into paused_results values('case3_missing_stale_threshold','PASS','predicate blocks advancement; real authenticated completion RPC rejects current missing trust before write with22023');
 update public.lesson_assets set duration_seconds=100,duration_verification_source='Synthetic current trusted source' where id=asset;
 insert into public.media_progress(profile_id,asset_id,covered_intervals) values(b,asset,'[[0,94]]');
 assert not app_private.course_watch_met(b,l);
 update public.media_progress set covered_intervals='[[0,95]]' where profile_id=b and asset_id=asset;
 assert app_private.course_watch_met(b,l);
 assert app_private.course_watch_met(a,l) and app_private.course_lesson_unlocked(a,l2);
 insert into paused_results values('case5_restored_trust_and_94_95','PASS','seeded interval boundary only; not real playback/sampling');
 update public.lesson_progress set worksheet_status='completed',worksheet_answers='{"1":"Synthetic answer"}',status='completed' where profile_id=a and lesson_id=l;
 select completed_at into history_time from public.lesson_progress where profile_id=a and lesson_id=l;
 assert history_time is not null;
 insert into public.lesson_private_notes(profile_id,lesson_id,body) values(a,l,'Synthetic owner-only note');
 update public.lesson_assets set duration_seconds=null where id=asset;
 assert (select status='completed' and completed_at=history_time from public.lesson_progress where profile_id=a and lesson_id=l);
 assert app_private.course_lesson_unlocked(a,l) and not app_private.course_lesson_unlocked(a,l2);
 insert into paused_results values('case4_completed_history','PASS','synthetic completion earned from valid seeded coverage before trust removal; note RPC cannot succeed while paused');
 denied:=false;begin update public.lesson_assets set provider_ref='replacement' where id=asset;exception when check_violation then denied:=true;end;assert denied;
 update public.lesson_assets set status='draft' where id=asset;
 insert into public.lesson_assets(lesson_id,asset_type,provider,provider_ref,status,duration_seconds,duration_verification_source) values(l,'video','youtube','replacement','active',100,'Synthetic replacement verification') returning id into replacement;
 assert not app_private.course_watch_met(a,l) and not app_private.course_lesson_unlocked(a,l2);
 insert into paused_results values('case8_identity_provenance','PARTIAL','watched identity replacement rejected; new asset has no borrowed credit; stored NULL/blank provenance injection not attempted; existing normalizer supplies trusted_database_configuration');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated','aal','aal1')::text,true);
 perform set_config('request.method','GET',true);perform set_config('request.path','/lesson_progress',true);
 execute 'set local role authenticated';
 assert (select count(*)=1 from public.lesson_progress where profile_id=a and lesson_id=l),'Safe own read control missing';
 assert not exists(select 1 from public.lesson_private_notes where profile_id=a),'Paused notes exposed';
 denied:=false;begin insert into public.media_progress(profile_id,asset_id,percent_watched) values(a,replacement,100);exception when sqlstate 'PT503' then denied:=true;end;assert denied;
 insert into paused_results values('case6_forged_percentage','BLOCKED_BY_MAINTENANCE','PT503 denies forged write before RLS/percentage logic; not independent unpaused proof');
 denied:=false;begin perform public.lockliel_sample_media(a,replacement,99,true);exception when sqlstate 'PT503' then denied:=true;end;assert denied;
 insert into paused_results values('case7_seek_sample','BLOCKED_BY_MAINTENANCE','PT503 proves pause, not seek-specific runtime acceptance');
 perform pg_sleep(0.31);
 denied:=false;begin perform public.lockliel_save_lesson(a,l,0,'{"1":"Synthetic answer"}','Synthetic edited note',false);exception when sqlstate 'PT503' then denied:=true;end;assert denied;
 insert into paused_results values('completed_note_save','BLOCKED_BY_MAINTENANCE','positive note persistence cannot be demonstrated with maintenance ON');
 execute 'reset role';
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'session_id',sb,'role','authenticated','aal','aal1')::text,true);
 execute 'set local role authenticated';
 assert not exists(select 1 from public.lesson_progress where profile_id=a and lesson_id=l),'B read A progression';
 assert not exists(select 1 from public.lesson_private_notes where profile_id=a),'B read A notes';
 denied:=false;begin perform public.lockliel_save_lesson(a,l,0,'{}','',false);exception when insufficient_privilege then denied:=true;end;assert denied;
 insert into paused_results values('A_B_ownership','PASS','authenticated safe own read exists; B cannot read A progress or save as A; notes closed');
 execute 'reset role';perform set_config('request.jwt.claims','{}',true);
 assert (select body='Synthetic owner-only note' from public.lesson_private_notes where profile_id=a and lesson_id=l);
 assert (select status='completed' and completed_at=history_time from public.lesson_progress where profile_id=a and lesson_id=l);
 assert public.lockliel_course_cutover_status()='{"paused":true,"schemaReady":true,"protocol":"278-v1"}'::jsonb;
end;$test$;
select jsonb_agg(to_jsonb(r) order by name) from paused_results r;
